# Generated by Django 4.2.14 on 2024-07-10 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='MyModel',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
